### ISSUE TITLE
Croppa::url does not point at the crops_dir

### ISSUE THREAD

**Issue by beeglebug** [BKWLD/croppa#101]
According to the `Crops in a sub-directory` section of the examples page: `https://github.com/BKWLD/croppa/wiki/Examples` I should be able to call Croppa::url with a source url and have it transformed to point at the crops directory ('/images/file.jpg' becomes '/images/thumbsfile.jpg' in the example).

I cannot get this to work, Croppa::url seems to do nothing more than add the arguments to the end, without adjusting the path.

Am I missing something? My config is:

```
'src_dir' => public_path('/images'),
'crops_dir' => public_path('/thumbs'),
'path' => 'thumbs\/(.*)$',
```

If I call Croppa::url('images/foo.jpg',100,100) i get `images/foo-100x100.jpg`, but was expecting `thumbs/foo-100x100.jpg`

**Comment by weotch** [comment]
Looks like I omitted a param from that example. [I've updated it now](https://github.com/BKWLD/croppa/wiki/Examples#crops-in-a-sub-directory).  

```php
'src_dir'    => public_path().'/images',
'crops_dir'  => public_path().'/images/thumbs',
'path'       => 'images/(?:thumbs/)?(.*)$',
'url_prefix' => '/images/thumbs/',
```

And I added a test to specifically for your case above.
