### ISSUE TITLE
Token missmatch

### ISSUE THREAD

**Issue by vics80** [BKWLD/croppa#102]
I have 2 projects that share some images. The Croppa plugin was working fine until a few weeks ago but now I get this error:
NotFoundHttpException
Token missmatch
How can I configure this token?

**Comment by weotch** [comment]
You could set [`signing_key` to `false`](https://github.com/BKWLD/croppa/blob/master/src/config/config.php#L90) to disable the automatic signing of URLs with tokens.  

I'm surprised this is happening though.  On these projects, are there some cases where you are generating URLs without using `Croppa::url()`?

**Comment by vics80** [comment]
No, but I forgot to republish the config file.

Really thanks!

**Comment by weotch** [comment]
Ah, i see.  So is it working now?

**Comment by vics80** [comment]
Yes, all right!

**Comment by weotch** [comment]
Sweet!
