### ISSUE TITLE
Still does not delete crops.

### ISSUE THREAD

**Issue by d-lamers** [BKWLD/croppa#103]
I got time to test the new version but sadly croppa still does not delete the crops as you can see in this picture (It uses standard config. No changes)

![schermafbeelding 2015-07-29 om 12 58 09](https://cloud.githubusercontent.com/assets/3164508/8955976/c8e8fed2-35f1-11e5-95d7-f21188bdb0ea.png)

**Comment by mgsmus** [comment]
I also can confirm that croppa doesn't delete crops.

**Comment by GregoryClaeyssens** [comment]
Same issue, deletion does not work...

**Comment by osaris** [comment]
+1

**Comment by elephantux** [comment]
+1

**Comment by weotch** [comment]
Ah ha, I've figured out how to reproduce this ... if the files are directly in the /uploads dir it fails as you described.  If they are in a subdir (like `/uploads/01/test-2.png`) the delete succeeds. Looking into a fix now.

**Comment by weotch** [comment]
Ok, pushing up a fix and tagging as 4.3.0

![](http://yo.bkwld.com/010A0S2B0x2V/Screen%20Recording%202016-01-22%20at%2010.02%20AM.gif)
