### ISSUE TITLE
Refactor to use Intervention for image manipulation

### ISSUE THREAD

**Issue by nicolasbinet** [BKWLD/croppa#110]
Is-is possible to user Croppa with imagick.
It seems to have better support/conservation of EXIF metadata when resizing images

**Comment by weotch** [comment]
I would like to do refactor to use http://image.intervention.io/ rather than PHPThumb.  If I do that, it would allow for imagick support.

**Comment by nicolasbinet** [comment]
Sure that would do the trick.
In fact for my problem, imagick is not the magic wand, if I use thumbnail it kills the EXIT datas, but resize works great.
