### ISSUE TITLE
The "Src outside of doc root" example is probably wrong

### ISSUE THREAD

**Issue by rulatir** [BKWLD/croppa#113]
The last example on this page:

https://github.com/BKWLD/croppa/wiki/Examples

is probably wrong. The specification section specifies a path for crops that contains a directory named 'thumbs', but the word 'thumbs' appears neither in the example configuration nor in the example invocation of Croppa::url().

Please clarify and/or fix.

**Comment by weotch** [comment]
You're right, fixed, thanks
