### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Read1337** [BKWLD/croppa#114]
Hello, i'm trying to use croppa but i cant make it work.

I follow the instructions and installed with composer in laravel 5.

I have the configuration file with the example config.

return [
    'src_dir' => public_path().'/uploads',
    'crops_dir' => public_path().'/uploads',
    'path' => 'uploads/(.*)$',
];

I have a test.jpg image in the public/uploads folder, and im calling the Croppa::url like this:
Croppa::url('/uploads/test.jpg', 20, 20);

I don't get any error, no new file added to the uploads folder and also the url method doesn't show me any image, just a broken url.

**Comment by weotch** [comment]
What URL is `Croppa::url()` outputting?

**Comment by Read1337** [comment]
Its outputting this:
/uploads/test-20x20.jpg

**Comment by weotch** [comment]
To clarify, calling `Croppa::url()` doesn't create the image.  Requesting the path (like from web browser) `/uploads/test-20x20.jpg` creates the image and returns it.  If you request that path, are you seeing the image get created?

**Comment by Read1337** [comment]
Nope running the url in the browser like this "mydomain.com/public/uploads/test-20x20.jpg" its giving me a 404 error.

**Comment by weotch** [comment]
What about `http://mydomain.com/uploads/test-20x20.jpg` (it's unusual to put `public` in the request)

**Comment by Read1337** [comment]
Same thing. 404 Error, and no file created.

**Comment by Read1337** [comment]
I copied my project and put it in MAMP and worked. Its something with my development server. Do you have any idea what could be?

**Comment by weotch** [comment]
So maybe an issue with nginx?  You could check out these issues: https://github.com/BKWLD/croppa/issues?utf8=%E2%9C%93&q=is%3Aissue+nginx.  I don't use nginx yet myself, so I don't have much advice

**Comment by weotch** [comment]
Some nginx docs were added in #118, maybe they'll help ya
