### ISSUE TITLE
H5BP HTTP Nginx server cache

### ISSUE THREAD

**Issue by sdebacker** [BKWLD/croppa#117]
When using [Nginx HTTP server boilerplate configs](https://github.com/h5bp/server-configs-nginx), Croppa has a problem because of 

```bash
location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
  expires 1M;
  access_log off;
  add_header Cache-Control "public";
}
```

Adding ```error_page 404 = /index.php?$query_string;``` solves the problem, perhaps it should be mentioned in the readme? What do you think?

**Comment by weotch** [comment]
Yeah, I'm cool with that ... I still don't have any first hand nginx experience so I defer to you on this.  Do you wanna PR it?

**Comment by sdebacker** [comment]
Yes, I'm just not sure where to put it in the doc, do you have an idea ?

**Comment by weotch** [comment]
How about as in "Nginx" block under [Installation](https://github.com/BKWLD/croppa#installation)

**Comment by sdebacker** [comment]
Ok, nice.

**Comment by weotch** [comment]
Added in #118
