### ISSUE TITLE
Error during installation on Laravel 5.2

### ISSUE THREAD

**Issue by AleBonatti** [BKWLD/croppa#119]
Hi,
on _composer require "bklwd/croppa"_ I get a bunch of errors:

_Your requirements could not be resolved to an installable set of packages._

  _Problem 1_
    _- Installation request for bkwld/croppa ^4.3 -> satisfiable by bkwld/croppa[4.3.0]._
    _- Conclusion: remove symfony/http-foundation v3.0.2_
    _- Conclusion: don't install symfony/http-foundation v3.0.2_

etc...

I'm trying to install on Laravel 5.2.
When pasting _"bkwld/croppa": "^4.3"_ in composer.json e then launching _composer update_, installation works, but symfony/http-foundation 3.0 is removed for version 2.8 (as well as symfony kernel).
What should I do?

**Comment by bumikk** [comment]
Indeed. Ive got same issue.
Laravel 5.3 is based on Symfony 3 so composer cannot resolve Croppa dependencies.

**Comment by weotch** [comment]
I'll skim to see if the Symfony classes I'm using have changed much between 2 and 3.  Ideally I can loosen that version constraint.

**Comment by weotch** [comment]
Try `dev-master` and let me know if you run into any issues.

**Comment by AleBonatti** [comment]
dev-master installation works fine now.
Thank you.
