### ISSUE TITLE
Add a `cover` option

### ISSUE THREAD

**Issue by weotch** [BKWLD/croppa#121]
`cover` is a type of resize.  Given a width and height (both required) it will produce the smallest crop possible without upsizing while still filling the size.  

So, for instance, if you do `Croppa::url('file.jpg', 200,200)` on a 400x200 image...

- default - Produces a 200x200 image
- `resize` - Produces a 200x100 image
- `cover` - Will produce a 400x200 image

**Comment by weotch** [comment]
Eh, don't think we need this afterall

**Comment by KeithTurkowski** [comment]
Cover seems like a good option to have, is there way to achieve that with the current options?

with a carousel 600x600px, and Croppa::url('file.jpg', 600,600), then a 600x1200 image will be reduced to 300x600, and if I'm using the 'background-size: cover' css, then the image will be pixelated.

If I do Croppa::url('file.jpg', 600, null), the same problem.

If I do Croppa::url('file.jpg', null,600), the issue still exists for portrait aspect ratios, e.g. 1200x600.

I guess the best solution with the current options would be to choose a realistic "extreme aspect ratio" and then scale for that. e.g. extreme aspect ratio"3:4" -> Croppa::url('file.jpg', null,800)
