### ISSUE TITLE
No thumb generation with croppa.js

### ISSUE THREAD

**Issue by sdebacker** [BKWLD/croppa#122]
Hello, I tested croppa.js and I saw that the thumb generation is not working because there is no signing key generated. Do you have some advice about that ?

**Comment by weotch** [comment]
Yeah, you'll need to disable the signing key feature by setting `signing_key` to `false` in the config.  I recommend you *do* set a `max_crops` value in that case.

**Comment by sdebacker** [comment]
ok, this information should be mentioned in the readme.
Moreover, it would be great to implement the functionality with javascript.
