### ISSUE TITLE
Call to undefined method Bkwld\Croppa\Helpers::render()

### ISSUE THREAD

**Issue by darrenw16** [BKWLD/croppa#129]
Ive installed croppa into my laravel 5.2 project. When I run this code from my controller
Croppa::render(Croppa::url('/files/images/'.$name, 800, 600));

I get the following error 
Call to undefined method Bkwld\Croppa\Helpers::render()

Also after doing the composer install after completing all 3 install steps I dont see any config file in my config folder do I need to run some php artisan command to generate it

**Comment by darrenw16** [comment]
Got rid of the config error by running php artisan vendor:publish --provider="Bkwld\Croppa\ServiceProvider"... I think this should be added to the install instructions

**Comment by weotch** [comment]
@dannoso can wanna look into why someone would need to publish the config for `Croppa::render` to work?

**Comment by darrenw16** [comment]
@weotch I think I may have confused you my croppa::render still wont work... but to generate the config in laravel you need to run php artisan vendor:publish --provider="Bkwld\Croppa\ServiceProvider" so I was suggesting you add it to the install instructions.

If you could help me get the croppa::render to work that would be great. I followed the install instructions and then add use Croppa to my controller but I get the error when I call the controller Call to undefined method Bkwld\Croppa\Helpers::render()

**Comment by dannoso** [comment]
@darrenw16 can you please attach the lavavel.log tail and the config file setting?
It's most likely there's something wrong in config file causing a runtime error.

**Comment by darrenw16** [comment]
My laravel log

```
[2016-07-06 17:27:34] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Bkwld\Croppa\Helpers::render()' in /var/www/public/pim/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:217
Stack trace:
#0 {main}  
```

**Comment by darrenw16** [comment]
my config file @dannoso 
``<?php return array(

	/*
	|-----------------------------------------------------------------------------
	| Image source and crop destination
	|-----------------------------------------------------------------------------
	*/

	/**
	 * The directory where source images are found. This is generally where your
	 * admin stores uploaded files. Can be either an absolute path to your local
	 * disk (the default) or the name of an IoC binding of a Flysystem instance.
	 *
	 * @var string     Absolute path in local fileystem
	 *      | string   IoC binding name of League\Flysystem\Filesystem
	 *      | string   IoC binding name of League\Flysystem\Cached\CachedAdapter
	 */
	'src_dir' => public_path().'/files/images',

	/**
	 * The directory where cropped images should be saved. The route to the
	 * cropped versions is what should be rendered in your markup; it must be a
	 * web accessible directory.
	 *
	 * @var string     Absolute path in local fileystem
	 *      | string   IoC binding name of League\Flysystem\Filesystem
	 *      | string   IoC binding name of League\Flysystem\Cached\CachedAdapter
	 */
	'crops_dir' => public_path().'/files/images/crops',

	/**
	 * Maximum number of sizes to allow for a particular source file. This is to
	 * limit scripts from filling up your hard drive with images. Set to false or
	 * comment out to have no limit. This is disabled by default because the
	 * `signing_key` is a better prevention of malicious usage.
	 *
	 * @var integer | boolean
	 */
	'max_crops' => false,


	/*
	|-----------------------------------------------------------------------------
	| URL parsing and generation
	|-----------------------------------------------------------------------------
	*/

	/**
	 * A regex pattern that is applied to both the src url passed to
	 * `Croppa::url()` as well as the crop path received when handling a crop
	 * request to find the path to the src image relative to both the src_dir
	 * and crops_dirs. This path will be used to find the source image in the
	 * src_dir. The path component of the regex must exist in the first captured
	 * subpattern. In other words, in the `preg_match` $matches[1].
	 *
	 * @var string
	 */
	'path' => 'files/images/(.*)$',

	/**
	 * A regex pattern that works like `path` except it is only used by the
	 * `Croppa::url($url)` generator function. If the $path url matches, it is
	 * passed through with no Croppa URL suffixes added. Thus, it will not be
	 * cropped. This is designed, in particular, for animated gifs which lose
	 * animation when cropped.
	 *
	 * @var string
	 */
	'ignore' => '\.(gif|GIF)$',

	/**
	 * A string that is prepended to the path captured by the `path` pattern
	 * (above) that is used to from the URL to crops.
	 */
	// 'url_prefix' =>  '//'.Request::getHttpHost().'/uploads/',        // Local
	// 'url_prefix' => 'https://your-bucket.s3.amazonaws.com/uploads/', // S3

	/**
	 * Reject attempts to maliciously create images by signing the generated
	 * request with a hash based on the request parameters and this signing key.
	 * Set to 'app.key' to use Laravel's `app.key` config, any other string to use
	 * THAT as the key, or false to disable.
	 *
	 * If you are generating URLs outside of `Croppa::url()`, like the croppa.js
	 * module, you can disable this feature by setting the `signing_key` config
	 * to false.
	 *
	 * @var string|boolean
	 */
	'signing_key' => 'app.key',

	/**
	 * The PHP memory limit used by the script to generate thumbnails. Some
	 * images require a lot of memory to perform the resize, so you may increase
	 * this memory limit.
	 */
	'memory_limit' => '128M',

	/*
	|-----------------------------------------------------------------------------
	| Image settings
	|-----------------------------------------------------------------------------
	*/

	/**
	 * The jpeg quality of generated images. The difference between 100 and 95
	 * usually cuts the file size in half. Going down to 70 looks ok on photos
	 * and will reduce filesize by more than another half but on vector files
	 * there is noticeable aliasing.
	 *
	 * @var integer
	 */
	'jpeg_quality' => 95,

	/**
	 * Turn on interlacing to make progessive jpegs.
	 *
	 * @var boolean
	 */
	'interlace' => true,

	/**
	 * If the source image is smaller than the requested size, allow Croppa to
	 * scale up the image. This will reduce in quality loss.
	 *
	 * @var boolean
	 */
	'upscale' => false,

);

**Comment by mgsmus** [comment]
render method in Helpers.php is only available in dev-master, doesn't exists in releases.
@weotch ping

**Comment by weotch** [comment]
Tagged as 4.5.0
