### ISSUE TITLE
Should url() create a resized image? Render works, but url doesn't

### ISSUE THREAD

**Issue by Photoshopper** [BKWLD/croppa#136]
I have a test.jpg in an upload directory.

I assumed that Croppa::url should create and return new cropped image, but it doesn't work
`
<img src="<?= Croppa::url('/uploads/test.jpg', 200, 200) ?>" />
`

output is:
`
<img src="/uploads/test-200x200.jpg?token=8dfb5d2c95327d00a1550f2fc52f2b6b">
`

but "test-200x200.jpg" wasn't created

**Comment by weotch** [comment]
Note, the file isn't created until you make a HTTP request for `/uploads/test-200x200.jpg?token=8dfb5d2c95327d00a1550f2fc52f2b6b`.  Did you do that?

**Comment by Photoshopper** [comment]
I'm getting 404 error when I try to open http://mydomain/uploads/test-200x200.jpg?token=8dfb5d2c95327d00a1550f2fc52f2b6b

**Comment by weotch** [comment]
Can you confirm that when you go to http://mydomain/uploads/test.jpg you see your image?

**Comment by Photoshopper** [comment]
yes

**Comment by Photoshopper** [comment]
I use asgardcms and it seems like they conflict. I tried a clear laravel setup and everything works there

**Comment by weotch** [comment]
Ahhhh my guess is maybe they are handling the route before Croppa can act. Gonna close this, but feel free to submit a pr if you find a way to resolve.

**Comment by Photoshopper** [comment]
Thank you for your guess. It helped me to solve the problem.
In asgardcms, you should register ```Bkwld\Croppa\ServiceProvider::class``` before ```Modules\Core\Providers\AsgardServiceProvider::class```
