### ISSUE TITLE
Croppa: Crop already exists

### ISSUE THREAD

**Issue by nickbr5** [BKWLD/croppa#137]
Hi,

I'm having the issue that i can only generate cropped images once. Second time i get the crop already exists exception.
This is the url i use in my view: /media/albums/blend/Blend_(43_van_80)-300x200.jpg
In the config file i have:
'src_dir' => public_path().'/media',
'crops_dir' => public_path().'/media/cropped',
'path' => 'media/(.*)$',

I solved this problem now by changing the render function in Handler.php. I remove the check if cropsAreRemote, so i always check if the crop exists.

Am i missing something important, since nobody seems to have this problem?

Thanks!

**Comment by weotch** [comment]
You're running `4.5.1` right?  It could be a regression caused by changes in 4.5.x ... It sounds like the `cropsAreRemote()` function is always returning true for you, does that sound right?

**Comment by sdebacker** [comment]
Same problem for me, with Croppa 4.6.
My config:

**filesystems**

        'uploads' => [
            'driver' => 'local',
            'root' => storage_path('app/public/uploads'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        'crops' => [
            'driver' => 'local',
            'root' => storage_path('app/public/crops'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

**Croppa**

    'src_dir' => 'filesystem.uploads.driver',
    'crops_dir' => 'filesystem.crops.driver',
    'path' => 'uploads/(.*)$',

**Comment by eliysha** [comment]
Hi
I have the same issue. Because `cropsAreRemote()` is returning false as I'm running with local filesystem.

I don't get why there'is this part

```
// If the crops_dir is a remote disk and if the crop has already been
        // created.  If it has, just return that path.
        if ($this->storage->cropsAreRemote()
        && $this->storage->cropExists($crop_path)) {
            return $crop_path;
        }
```

IMO we shouldn't check `$this->storage->cropsAreRemote()` every time
