### ISSUE TITLE
failed to resize GIF files

### ISSUE THREAD

**Issue by ahmadalukah** [BKWLD/croppa#141]
Hi, ! 
First I want to thank you so much for this amazing package..

It works perfectly except with gif files, they are not being resized. so is there an issue with gif files or is it from my side?
thank you !

**Comment by weotch** [comment]
The default config ignores gifs.  This is to prevent animated gifs from getting cropped and losing their animation.

https://github.com/BKWLD/croppa/blob/master/src/config/config.php#L60-L69

If you set `ignore` to an empty string, it will resize gifs.
