### ISSUE TITLE
Crop on upload ?

### ISSUE THREAD

**Issue by ahmadalukah** [BKWLD/croppa#142]
Hi, Thanks for this amazing package, I've been using it for my app and it's amazing !

I want to ask if there is a way to use this package to crop images before saving them,, something like:

```
$cropped= Croppa::render($request->file('thumbnail'), 300, 200);
```

**Comment by weotch** [comment]
Awesome!  Not sure what you mean by "before saving them".  Like, in your example, what is `$cropped` expected to be?  The URL of the image?
