### ISSUE TITLE
Having Issues saving cropped files on s3 

### ISSUE THREAD

**Issue by afaridanquah** [BKWLD/croppa#150]
I am able to save to s3 but crop resizing on s3 is not working for me . Below is my config file.Please check if am missing anything here.

croppa.php

   'src_dir' => 's3',
   'crops_dir' => 's3',
   'url_prefix' => 'https://s3-us-west-2.amazonaws.com/admin-redriver/uploads/'

on s3 bucket i am uploads dir.

**Comment by sdebacker** [comment]
Should work better with the new version 6.
