### ISSUE TITLE
Absolute Paths in src

### ISSUE THREAD

**Issue by Ande1232** [BKWLD/croppa#151]
Hi guys, sorry but I did not really understand how to customize the link...

The images are cut perfectly, and the package is really fantastic.

How do I get the absolute path in my pictures?  In my html i have:

`<img src="/upload/news/news_27a3f8cce39fb511bbd1ef65d10b7001-122x68-quadrant(T).jpg>`

While I would

`<img src="http://domain.com/upload/news/news_27a3f8cce39fb511bbd1ef65d10b7001-122x68-quadrant(T).jpg>`

Furthermore, How do i customize url, changing "quadrant(T)" with anything I want?

I noticed another problem... I have the original image in upload\news, while thumbnails are stored correctly in upload\thumbs\news, But the website take the original address

**Comment by Ande1232** [comment]
for the absolute path, i have resolved with:

`{{Croppa::url($img, 122, 68, array('quadrant' => 'T'))}}`

But if I change the directory where I need to save the thumbs from /upload/news to /upload/thumbs/news, Because the link shown is /upload/news?

In fact, if I see the image "/upload/news/news_028dd3729c0ebe23149e3f9c7fe62af2-404x202-quadrant(C).png" Which actually exists in /upload/thumbs/news/, I'm shown the error:

`(1/1) Exception
Croppa: Crop already exists at news/news_867ee1aaf272319809d5c0d72cd5a774-404x202-quadrant(C).jpg. You probably
have a misconfiguration. Make sure that the URL to your crop can be
transformed by the `path` config to your `crop_dir`.`

**Comment by sdebacker** [comment]
Should work better with the new version 6.
