### ISSUE TITLE
Issue with S3 image

### ISSUE THREAD

**Issue by rennymroy** [BKWLD/croppa#152]
I am able to save to s3 bucket but crop resizing to local is not working for me . Below is my config file.Please check if am missing anything here.

croppa.php

'src_dir' => 's3',
'crops_dir' => public_path().'/images',
'path' => 'images/(.*)$'

**Comment by xavitb3** [comment]
Hi! Did you do anything besides what the documentation states to save images to s3? I'm using TypiCMS and following the steps in the documentation does not seem to work
