### ISSUE TITLE
croppa:purge artisan command not working

### ISSUE THREAD

**Issue by ryanscherler** [BKWLD/croppa#153]
Seems that the Artisan CLI `php artisan croppa:purge` command is no longer working with the latest release of Laravel. Is there a different way of executing this command now?

**Comment by weotch** [comment]
Ahh, yeah, it needs to have the `fire` changed to `handle` per 5.5.  I'll fix that and add auto-discovery very soon (like today or this weekend)

**Comment by ryanscherler** [comment]
Sounds great - Thanks Robert!

**Comment by weotch** [comment]
Ha, I didn't get to this like I thought, been slammed.  Still on my radar though...

**Comment by weotch** [comment]
Tagged in 4.6.0 now

**Comment by sdebacker** [comment]
Thank you!
