### ISSUE TITLE
config parameter to explicit availlable size

### ISSUE THREAD

**Issue by Goopil** [BKWLD/croppa#155]
Hello there thanks for your work !

Is there any possibility to define a fixed sets of size that croppa should response to ? 

I'm using your package with [unisharp](https://github.com/UniSharp/laravel-filemanager) package to provide differents sizes for differents devices (with srcset). But i want to fix the possible size handling to prevent unneed sizes. I'm using it in a decoupled js app so the csrf token is not an option for me.

Any advice ?

**Comment by weotch** [comment]
Not exactly.  You can set a limit on the number of crops that will be created, though: https://github.com/BKWLD/croppa/blob/master/src/config/config.php#L31-L39
