### ISSUE TITLE
Crops directory in storage folder (Private)

### ISSUE THREAD

**Issue by laziaf** [BKWLD/croppa#157]
How to put cropped image in storage folder?

**Comment by weotch** [comment]
In the config file:

```php
'src_dir' => public_path().'/storage',
'crops_dir' => public_path().'/storage',
'path' => 'storage/(.*)$',
```

I'm doing this on a current project and it's working well.

**Comment by laziaf** [comment]
No, your solution only make new folder named 'storage' in public path to store image thumbnail. What i'm trying to do is to create it in laravel storage folder app/storage/uploads to prevent unauthenticated user to access it. something like

'src_dir' => storage_path().'/uploads',
'crops_dir' => storage_path().'/uploads',
'path' => 'storage/(.*)$',

But that not working and not creating thumbnail / cropped image in storage folder

**Comment by weotch** [comment]
How do you intend to show the crops if they are not accessible publically?  Croppa is designed to make publically accessible crops so that the web server can serve them directly on subsequent requests, thus bypassing the PHP / Laravel stack.  It may not be the right fit for your use case.

**Comment by christiant79** [comment]
Hi, I, too, have the scenario where I needed the images and the crops protected.
It works with following settings in laravel 5.8:
'src_dir' => storage_path().'/uploads',
'crops_dir' => storage_path().'/uploads',
'path' => '/uploads/(.*)$', /* important is the slash in the begining */

you will need a route:
Route::get('/uploads/{user}/{file}','ImageController@get_upload_files')->middleware('auth');

and a controller to check access:
public function get_upload_files(User $user_id, $filename)
{
    abort_if(\Gate::denies('update', $user_id), 403);
    return response()->file(storage_path('uploads/'.$user->id.'/'.$filename));
}
