### ISSUE TITLE
Crop already exists 

### ISSUE THREAD

**Issue by greal** [BKWLD/croppa#159]
Hello!
After creating the preview, the error is:

`
Croppa: Crop already exists at cars/colors/599161845b2c3-100x_-resize.jpg. You probably
have a misconfiguration. Make sure that the URL to your crop can be
transformed by the `path` config to your `crop_dir`.
`

Looked at the source code, and it looks like a flaw, for remote it should work without problems, but for local ones it will always be created. I have the default settings.

I removed the scan on the remote disk
```
if ($this->storage->cropExists($crop_path)) {
        return $crop_path;
}
```

I do not know, maybe I'm not right, if that's how it is, please tell me how it's needed.

**Comment by eliysha** [comment]
Hi
I have the same issue. Because `cropsAreRemote()` is returning false as I'm running with local filesystem.

I don't get why there is this part

```
// If the crops_dir is a remote disk and if the crop has already been
        // created.  If it has, just return that path.
        if ($this->storage->cropsAreRemote()
        && $this->storage->cropExists($crop_path)) {
            return $crop_path;
        }
```

IMO we shouldn't check `$this->storage->cropsAreRemote()` every time

**Comment by oza75** [comment]
Check if the symbolic link of the storage has been created! If it's not the case run : `php artisan storage:link`

**Comment by jordanade** [comment]
Everything seems to work but I get this error **sporadically**. I am using local crops and S3 originals.

**Comment by stefnats** [comment]
Maybe a quick hint, sometimes we have traffic peaks and i think this could cause the error.

Two requests at the same time and "PHP redirects traffic to croppa": first one creates the crop and second one sees that the crop already exists and throws the error. Is this a possible scenario as i think it is?
Once the crop exists at "check time", it doesn't throw an error anymore. It's hard to catch actually, i never had this issue but sometimes it shows up in sentry.

**Comment by christiant79** [comment]
as I mentioned in https://github.com/BKWLD/croppa/issues/157 aswell, if this would be fixed the scenario where you want to use storage_path() instead of public_path() would work too.

**Comment by jordanade** [comment]
Any update on this?

**Comment by stefnats** [comment]
@jordanade I believe this project is not maintained anymore (unfortunately!). There are 2 PRs which could solve this, but the maintainer seems to be out of town for a while.

**Comment by sdebacker** [comment]
The new version 6 was just released.
