### ISSUE TITLE
Laravel version 5.6 support?

### ISSUE THREAD

**Issue by ItsRD** [BKWLD/croppa#163]
Currently there is no support for the new Laravel version 5.6, since symfony has been updated to 4.

`bkwld/croppa 4.7.0 requires symfony/http-foundation 2 - 3`

**Comment by weotch** [comment]
Thanks for the heads up, I'll drop an updated verison constraint into master shortly.

**Comment by weotch** [comment]
Can you change your version of croppa to `dev-master` and tell me if that fixes it _and_ that everything is working as intended?

**Comment by ItsRD** [comment]
Works fine for me! Tested it on an existing project

**Comment by weotch** [comment]
Nice.  Tagged as 4.7.1.

**Comment by ItsRD** [comment]
Awesome, thanks for the quick response!
