### ISSUE TITLE
Add Support to Laravel 6

### ISSUE THREAD

**Issue by jrmessias** [BKWLD/croppa#178]
Hello, may you add support to Laravel 6?

Tks

**Comment by adrenaxus** [comment]
Support for Laravel 6 would be terrific! Thumbs up! :D

**Comment by gsmeira** [comment]
I created a simple pull request #183 to solve this compatibility issue.

**Comment by adrenaxus** [comment]
Thank you @gsmeira.
I will try as soon as possible and check it out!

**Comment by adrenaxus** [comment]
Hello,

I tried to get it to work with Laravel 6.14 but was not successfull.

How can I install your pull request with the Laravel 6 compatibility fix using either composer require or composer.json?

I tried to install the master branch but it is not working, also referencing by commit #hash does not work... (I tried this approach: https://stackoverflow.com/questions/25878984/can-i-pull-a-specific-commit-with-composer)

Please clarify if Croppa will be available for Laravel 6 in the foresseable future. It's such a great package but it looks like development has somewhat stalled in the last year...

Thanks for any help!

**Comment by gsmeira** [comment]
Hi @adrenaxus,

Try this...

In the `require` section of your composer.json file put:

```json
"require": {
    "bkwld/croppa": "dev-master"
}
```

and add a `repositories` section like this:

```json
"repositories": [
    {
      "type": "git",
      "url": "https://github.com/BKWLD/croppa.git",
      "no-api": true
    }
]
``

**Comment by adrenaxus** [comment]
Hello @gsmeira,

Thank you very much for your reply! I was indeed able to install Croppa now on Laravel 6.15.

I published the configuration using `php artisan vendor:publish --tag=croppa`

I'm having an issue tho: I can visit my image: `http://domain.com/project/uploads/test.jpg` fine

But if I try: `http://domain.com/project/uploads/test-100x100.jpg` I get the following error:

**`Undefined offset: 1 in vendor/bkwld/croppa/src/Bkwld/Croppa/URL.php:163`**

I checked `vendor/bkwld/croppa/src/Bkwld/Croppa/URL.php` and it seems like the croppa config file is not loaded, `$this->config` is empty so it cannot succesfully execute the following line:

`preg_match('#'.$this->config['path'].'#', $path, $matches)`

Maybe you have an idea? Changing or even deleting the configuration file does not change anything so I guess it's not my configuration that's the issue...

Thanks again for your time and cheers

**Comment by adrenaxus** [comment]
I was able to solve the above mentioned issue by using 

`php artisan config:clear`
`php artisan cache:clear`
`php artisan route:clear`

Not sure why, but it did solve `Undefined offset: 1 in vendor/bkwld/croppa/src/Bkwld/Croppa/URL.php:163` problem.

I am now able to use Croppa with Laravel 6.15.1. 

Cheers everyone and thanks!
