### ISSUE TITLE
Upload crops to S3 and get correct url

### ISSUE THREAD

**Issue by tania-pets** [BKWLD/croppa#179]
I am trying to have both originals and crops to S3 bucket.

Using config 1. below, crops are not uploaded in S3, thus `{{ Croppa::url($image, 300) }}`

which gives something like `https://xxx.s3.eu-west-2.amazonaws.com/uploads/xxxx-300x_.jpg` does not find any files.

**`Bkwld\Croppa\Handler@handle` never gets called.

**Config 1.**
```
'src_dir' => 's3',
'crops_dir' => 's3',
'url_prefix' => 'https://' . env('S3_STORAGE_BUCKET') . '.s3.eu-west-2.amazonaws.com/'
```

Using config 2, does upload crops in S3 properly, but the `Croppa::url(....)`  returns local url since we have no url_prefix specified.

**Config 2.**
```
'src_dir' => 's3',
'crops_dir' => 's3',
//'url_prefix' => '' nothing here, it's commented
```

Can't find out how I can upload crops to S3 **AND** generate correct url.

Seems like I need to unset the url_prefix for uploading (config 2) and set this to S3 url (config 1) for getting the correct url.

Am I missing something, or is this a bug?

Laravel 5.8
PHP 7.3.10

Thank you

**Comment by Askancy** [comment]
same problem, did you manage to configure crops and original in S3?

**Comment by tania-pets** [comment]
> same problem, did you manage to configure crops and original in S3?

Not really, I ended up using the config 2. and  use  a custom function to get the thumb url:

```
public function imageThumb($width, $image = null): string
{
	if (!$image || !Storage::cloud()->exists($image)) {
          return $this->getDefaultImage();
	}
	$url = Croppa::url($image, $width);
	$url = trim($url, '/');
	$cloudUrl = Storage::cloud()->url($url);
	Croppa::render(preg_replace('/\?.*/', '', urldecode($url)));
	return urldecode($cloudUrl);
}
```

**Comment by sdebacker** [comment]
New v6 should simplify the process.
