### ISSUE TITLE
PHPThumb returns Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by ahmadyousefdev** [BKWLD/croppa#184]
For some photos, I get this error exception `imagecreatefromstring(): gd-jpeg, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG` which shows the error is in this file `../vendor/weotch/phpthumb/src/GdThumb.inc.php` .  in the line 119 `$this->oldImage = imagecreatefromstring($this->fileName);`

How can we avoid such error ? Thanks!

**Comment by sdebacker** [comment]
Should work better with the new version 6.
