### ISSUE TITLE
Add support for Laravel 7

### ISSUE THREAD

**Issue by eboye** [BKWLD/croppa#186]
Can you make the support for L7?

Thanks a bunch.

**Comment by weotch** [comment]
We're not doing much Laravel development these days, so I think it's unlikely that I'll be getting to this in the short term.  I'd happily take a PR or take on additional maintainers.

**Comment by eboye** [comment]
Hi, I've made a PR ... seems to be working in my environment

https://github.com/BKWLD/croppa/pull/187

**Comment by weotch** [comment]
Thanks @eboye !

**Comment by eboye** [comment]
I just saw I left this one:

https://github.com/BKWLD/croppa/blob/master/composer.json#L2

just rename it back to yours.

And no prob. Thanks for the great lib. ;)
