### ISSUE TITLE
Can Croppa be used to serve images in next-gen formats?

### ISSUE THREAD

**Issue by DarkB0SsS** [BKWLD/croppa#192]
As google recommends this more and more, can this be done?

**Comment by weotch** [comment]
These places would need changing:

- https://github.com/BKWLD/croppa/blob/2ca553795085f21b77829053a9da0d1221d6cd77/src/Bkwld/Croppa/Handler.php#L132-L142
- https://github.com/BKWLD/croppa/blob/c31797f5790cbecc2591ef9ae9a20f71a7f9efcd/src/Bkwld/Croppa/URL.php#L14

The bigger problem is that this package (which does the image resizing) is quite old and I _doubt_ supports webp, etc: https://github.com/weotch/PHPThumb

Ideally this package would be replaced to something more modern, like Intervention.

**Comment by DarkB0SsS** [comment]
Thank you for the suggestion! I will try to figure out if I can make something in order to generate "WebP" images. Ill share the progress on the way. But as you mentioned, the problem will probably be PHPThumb.

**Comment by jordanade** [comment]
> If there is a way to refactor it to be more sufficient it will be perfect. I will appreciate all suggestions! Thank you!

This looks great, @DarkB0SsS! Any update on this? Could it be merged in, used in production?

**Comment by jordanade** [comment]
@DarkB0SsS it seems the ideal would be to save images both as their native format (image.jpg) as well as in webp (image.jpg.webp) and then use nginx/apache magic to serve one or the other depending on the client's capabilities.

**Comment by sdebacker** [comment]
The new version 6.0.0 make use of [Intervention Image](https://github.com/Intervention/image), so it supports WebP.

**Comment by jordanade** [comment]
Wonderful news @sdebacker. To be clear, there is still no way to convert jpegs to webps, correct? 
(Or even better, to produce both jpeg/pngs and webps so that another system can choose one or the other?)

**Comment by sdebacker** [comment]
It's correct, Croppa stay a Thumbnail generator and not a converter.
