### ISSUE TITLE
Add support for PHP 8

### ISSUE THREAD

**Issue by uziel-bueno** [BKWLD/croppa#194]
Hello, thanks for creating this awesome package.

I'm facing issues with composer when installing this dependency in a PHP 8 environment.

Can this be updated to be supported in PHP 8?

Much appreciated.

**Comment by tpaksu** [comment]
@weotch please release it..

**Comment by weotch** [comment]
✅

**Comment by tpaksu** [comment]
@weotch Thank you!! 🥇 🥇 🥇
