### ISSUE TITLE
How to transition to version 6.0.0?

### ISSUE THREAD

**Issue by jordanade** [BKWLD/croppa#207]
Before there was the option crops_dir:
`'crops_dir' => public_path().'/images',`

Now that's crops_disk:
`'crops_disk' => 'public',`

How to specify the directory that crops are stored in? I'm getting 404s on my crop URLs:
`https://my.domain.com/images/831/61d479929686a-440x_-resize-trim(0%2C122%2C720%2C856).jpeg?token=mytoken`

**Comment by sdebacker** [comment]
In `config/filesystems.php` you have to create another disk, for example:

```php
'crops' => [
    'driver' => 'local',
    'root' => storage_path('app/crops'),
    'url' => env('APP_URL').'/storage',
    'visibility' => 'public',
    'throw' => false,
],
```

and write `'crops_disk' => 'crops',` in the croppa configuration file.

**Comment by jordanade** [comment]
Thanks @sdebacker
