### ISSUE TITLE
Croppa: No pad color specified

### ISSUE THREAD

**Issue by b1nj** [BKWLD/croppa#222]
I have this exception  : "Croppa: Pad option needs width and height"
Color is not optional? However, there is a default color https://github.com/BKWLD/croppa/blob/18c948924fa53f1dbeff87f32d922d4e9d067d22/src/Image.php#L213

**Comment by sdebacker** [comment]
Color is default to white, but width and height are required, example: `<img src="{{ Croppa::url('storage/image.webp', 300, 200, ['pad']) }}" />`

**Comment by b1nj** [comment]
Sorry the message is Croppa: No pad color specified" with 
<img src="{{ Croppa::url('storage/image.webp', 300, 200, ['pad']) }}" />

https://github.com/BKWLD/croppa/blob/18c948924fa53f1dbeff87f32d922d4e9d067d22/src/Image.php#L211

**Comment by sdebacker** [comment]
Ok, I see, it should be fixed now.

**Comment by b1nj** [comment]
Perfect !
