### ISSUE TITLE
Add support for S3-type file storage

### ISSUE THREAD

**Issue by weotch** [BKWLD/croppa#52]
Croppa needs the crops it creates to be stored on the web server so that apache can directly serve them or Laravel can intercept the request and generate the image.  However, the source image doesn't **need** to be on the same box.  If the source image was uploaded to S3 (or any other box), Croppa could fetch it from there and then generate it's crops locally.

Thus, if you have 4 load balanced servers, each would maintain it's own directory of crops but the source images would live elsewhere, in a singular point.  It's wasteful from a disk space standpoint, but that's cheap.

**Comment by weotch** [comment]
Regarding "maybe its should be a key value pair" above ... it would be better to make the destination a separate config and squash #36 at the same time

**Comment by weotch** [comment]
Getting started on this now with this WIP plan: https://github.com/BKWLD/croppa/wiki/4.0-draft-spec

**Comment by weotch** [comment]
Some steps:

- [ ] Test creating PhpThumb instance from a string using contents from Flysystem

**Comment by weotch** [comment]
See https://github.com/BKWLD/croppa/releases/tag/4.0.0

**Comment by jordanade** [comment]
> If CloudFront was to expensive, a script (maybe something in the Croppa package) could check the file storage (s3) to see if the crop already exists and pass through the file. This isn't awesome, though, because the app server will have to spend time and bandwidth passing through files from S3.
> 
> Actually, maybe a better solution would be to actually return a 301 redirect (moved permanently) with an infinite expiration time to the actual full path on S3. I've seen some of Facebook's image handling to work this way, the browsers seem fine with it.
> 
> If that redirect could somehow happen at the web server level, that would be ideal. Like if Apache could "remember" that the 301 occurred at that address and handle before passing to PHP next time...

Is this solution possible with Croppa 4? I'm having trouble setting something like this up and there's no examples in the docs of storing crops on S3.
