### ISSUE TITLE
Images not outputted on first request of resize

### ISSUE THREAD

**Issue by mauserrifle** [BKWLD/croppa#74]
Hi,

When a thumb generates. No image output is received:

    Cache-Control: no-cache
    Connection: Keep-Alive
    Content-Encoding: gzip
    Content-Length: 20
    Content-Type: text/html; charset=UTF-8
    Date: Wed, 18 Feb 2015 14:06:42 GMT
    Keep-Alive: timeout=5, max=100
    Server: Apache/2.2.22 (Debian)
    Vary: Accept-Encoding
    X-Powered-By: PHP/5.5.21-1~dotdeb.1
    x-robots-tag: noindex, noarchive, nosnippet

After refreshing the URL it is served static. Something is bugged?

**Comment by mauserrifle** [comment]
Fix:

		$this->app->make('router')->get('{path}', function($path) use ($croppa) {
			$image = $croppa->generate($path);
			return \Response::stream(function() use ($image) {
				return $image->show();
			});

This response code has been deleted within the latest commits/merge!

**Comment by weotch** [comment]
Merged and tagged as 3.6.1.  Thanks!
