### ISSUE TITLE
Config setting: "host" not right

### ISSUE THREAD

**Issue by d-lamers** [BKWLD/croppa#78]
/**
    * Optional. Specify the host for Croppa::url() to use when generating
    * absolute paths to images.  If undefined and using Laravel, 
    * the `Request::host()` is used by default.
    */
    // 'host' => 'http://mydomain.com',

That is the setting I want to talk about, when your root url points to public/index.php, this works fine but when it doesn't for example http://mydomain.com/foo/public the images will point to the wrong url. This is in my case solved by changing the setting the setting to Config::get('app.url'). Even tough that might not be the best solution I think it has to change so it works by default even if the url is not root.

**Comment by weotch** [comment]
So, are you proposing the default config to:

```php
/**
* Optional. Specify the host for Croppa::url() to use when generating
* absolute paths to images.  If undefined and using Laravel, 
* the `Request::host()` is used by default.
*/
// 'host' => Config::get('app.url'),
```

?

**Comment by weotch** [comment]
I'm adding this as a recommendation in the upcoming 4.0 but I'm gonna leave the default using the current host since I believe a number of people (though maybe it's just us) leave the `app.url` config at it's default "localhost"
