### ISSUE TITLE
Route caching problem with Laravel 5

### ISSUE THREAD

**Issue by sdebacker** [BKWLD/croppa#81]
```php artisan route:cache``` return an error:
```
[LogicException]
Unable to prepare route [{path}] for serialization. Uses Closure.
```

**Comment by weotch** [comment]
Yeah, I see what you mean.  It appears you can't use route closures with route caching ... it's weird to me that an exception is thrown though ... like I would have expected it to just fall back.

Anyway, I guess I'll create a controller to handle that request, I've seen some other packages going that route too.

**Comment by weotch** [comment]
Try using `dev-master` now and let me know if that fixes it.

**Comment by sdebacker** [comment]
Yeah, it seems to work.

**Comment by sdebacker** [comment]
I can now run ```php artisan route:cache```

**Comment by sdebacker** [comment]
Version 3.6.2 ?

**Comment by weotch** [comment]
Done!

**Comment by jyothipotnuru31** [comment]
can't we catch routes which are using closures? ...if it is then for single peace of code also we have to write controller actions....

**Comment by weotch** [comment]
@jyothipotnuru31 I'm confused about what your issue is.  Can you expand on it?
