### ISSUE TITLE
Croppa::delete don't delete crops ?

### ISSUE THREAD

**Issue by sdebacker** [BKWLD/croppa#83]
Does deleteSrc method also delete crops ? It's seems not.

**Comment by sdebacker** [comment]
If it's not the case, you should change Docblocks and documentation

**Comment by weotch** [comment]
`Croppa::delete()` **should** delete src and crops (though I see that it isn't now).  `Storage::deleteSrc()` is working as intended and should only be the src.

Gonna push up a fix for `Croppa::delete()` now.

**Comment by sdebacker** [comment]
4.0.2 ?

**Comment by weotch** [comment]
Maybe, I'm looking into #84 right now and if that requires an update too, I wanna tag em both at once.

**Comment by weotch** [comment]
Ok, 4.0.2 is released now
