### ISSUE TITLE
File Exists

### ISSUE THREAD

**Issue by patrickml** [BKWLD/croppa#84]
I am currently getting this error

FileExistsException in Filesystem.php line 547:
File already exists at path: fall-560x560.png

Most likely its because it is trying to recreate the image even tho it already exists

this is how I am trying to access the image
~~~
<img src="{{\Croppa::url('/assets/images/fall.png', 560, 560)}}" alt=""/>
~~~

**Comment by weotch** [comment]
Which Croppa version are you using?

**Comment by patrickml** [comment]
The lasted one 4.0.1 After you fixed the helpers issue


Thank you,

Patrick Lewis
Lead Developer
Revolt Visual
828.461.6433
revoltvisual.com <http://revoltvisual.com/>

**Comment by patrickml** [comment]
Here is my Config Files

~~~
<?php return array(
	
	/*
	|-----------------------------------------------------------------------------
	| Image source and crop destination
	|-----------------------------------------------------------------------------
	*/

	/**
	 * The directory where source images are found.  This is generally where your 
	 * admin stores uploaded files.  Can be either an absolute path to your local 
	 * disk (the default) or the name of an IoC binding of a Flysystem  instance.
	 *
	 * @var string     Absolute path in local fileystem
	 *      | string   IoC binding name of League\Flysystem\Filesystem 
	 *      | string   IoC binding name of League\Flysystem\Cached\CachedAdapter
	 */
	'src_dir' => public_path().'/assets/images/uploads',

	/**
	 * The directory where cropped images should be saved.  The route to the 
	 * cropped versions is what should be rendered in your markup; it must be a 
	 * web accessible directory.
	 *
	 * @var string     Absolute path in local fileystem
	 *      | string   IoC binding name of League\Flysystem\Filesystem 
	 *      | string   IoC binding name of League\Flysystem\Cached\CachedAdapter
	 */
	'crops_dir' => public_path().'/assets/images/uploads/cropped',

	/**
	 * Maximum number of sizes to allow for a particular source file.  This is to 
	 * limit scripts from filling up your hard drive with images.  Set to falsey or 
	 * comment out to have no limit.
	 *
	 * @var integer | boolean
	 */
	'max_crops' => 12,


	/*
	|-----------------------------------------------------------------------------
	| URL parsing and generation
	|-----------------------------------------------------------------------------
	*/

	/**
	 * A regex pattern that compares against the Request path (`Request::path()`) 
	 * to find the image path to the image relative to the crops_dir. This path 
	 * will be used to find the source image in the src_dir. The path component of 
	 * the regex must exist in the first captured subpattern.  In other words, in 
	 * the `preg_match` $matches[1].
	 *
	 * @var string 
	 */
	'path' => 'images/(.*)$',

	/**
	 * A regex pattern that works like `path` except it is only used by the
	 * `Croppa::url($url)` generator function.  If the $path url matches, it is
	 * passed through with no Croppa URL suffixes added.  Thus, it will not be
	 * cropped.  This is designed, in particular, for animated gifs which lose 
	 * animation when cropped.
	 * 
	 * @var string 
	 */
	'ignore' => '\.(gif|GIF)$',

	/**
	 * A string that is prepended to the path captured by the `path` pattern
	 * (above) that is used to from the URL to crops.
	 */
//	 'url_prefix' =>  '//'.Request::getHttpHost().'/uploads/',        // Local
	// 'url_prefix' => 'https://your-bucket.s3.amazonaws.com/uploads/', // S3


	/*
	|-----------------------------------------------------------------------------
	| Image settings
	|-----------------------------------------------------------------------------
	*/

	/**
	 * The jpeg quality of generated images.  The difference between 100 and 95 
	 * usually cuts the file size in half.  Going down to 70 looks ok on photos 
	 * and will reduce filesize by more than another half but on vector files 
	 * there is noticeable aliasing.
	 *
	 * @var integer
	 */
	'jpeg_quality' => 95,

	/**
	 * Turn on interlacing to make progessive jpegs
	 *
	 * @var boolean
	 */
	'interlace' => true,
	
);

~~~

**Comment by weotch** [comment]
Have you tried this instead?

```
// The config
'path' => 'cropped/(.*)$',

// Your view
<img src="{{\Croppa::url('/assets/images/uploads/cropped/fall.png', 560, 560)}}" alt=""/>
```

This would:

- Return a URL of `/assets/images/uploads/cropped/fall-560x560.png` 
- Croppa would a source image at `public_path().'/assets/images/uploads/fall.png'` 
- Croppa would generate the crop at  `public_path().'/assets/images/uploads/cropped/fall-560x560.png'`
- On subsequent requests, Apache would handle the request and PHP wouldn't be trying to create a duplicate crop

However, I do want to fix that exception, too...

**Comment by weotch** [comment]
Actually, I'm gonna leave that exception.  My rationale:

If you are generating local crops, the app should never be asked to generate an image again if one already exists.  The URL to the crop should be one that the web server can directly fulfill from the filesystem on a subsequent request.  If you create a crop and on the next request the app tries to create that same crop again, then there is a config problem and an Exception should be thrown so you fix it.

I think I will capture the Exception and add some additional color to the message, though.

Also, let me know if my config suggestion fixes the issue for you.

**Comment by patrickml** [comment]
Thank you this did work. I was unaware that was how I should use this package. Thank you for looking into this for me.


Thank you,

Patrick Lewis
Lead Developer
Revolt Visual
828.461.6433
revoltvisual.com <http://revoltvisual.com/>

**Comment by weotch** [comment]
Awesome, gonna add some info to the docs to try and clear that up in the future.

**Comment by seltix5** [comment]
Hello,
I was struggling with this situation too and I have a question about this :
- The source images can be in different places (not all images are inside the same folder, the is subdirectories for organiaztion)
If I always need to cast url() with the thumb folder i will always need to send the src_folder as param because it will not be always the same.
Woldnt be more simple if the url() receive the original file path and if the thum exist return the thumb url by default ? or have a param to enable this option?
Thanks
