### ISSUE TITLE
Croppa not generate thumbnails

### ISSUE THREAD

**Issue by vtellez** [BKWLD/croppa#86]
Hi,

took months using this great project but for a couple of days ago I find that does not generate thumbnails of any size.

Looking at the apache logs and Laravel not see any reports or incident.

Any idea what could be happening?

Is there any way to tell Croppa display a default image when you can not generate a thumbnail?

Regards,

**Comment by weotch** [comment]
Hi @vtellez !  Did you recently update the package?  For instance, the new 4.0 release changed the config pretty significantly.  Also in #77 some users were reporting that some changes in 3.5 required some changed configs.

What version are you running and what version of Laravel are you running?

No, there isn't a default image option.

**Comment by vtellez** [comment]
We are using L4. This is our config for package:

<?php return array(
	
	// Directories to search for source files
	'src_dirs' => array(
		App::make('path.public'),
	),
	
	// Maximum number of sizes to allow for a particular
	// source file.  This is to limit scripts from filling
	// up your hard drive with images.  Set to false or comment
	// out to have no limit.
	'max_crops' => 50,

	// The jpeg quality of generated images
	'jpeg_quality' => 100,

	// Turn on interlacing to make progessive jpegs
	'interlace' => true,
	
);

**Comment by weotch** [comment]
1. What version of Croppa are you running?
2. What is the path to the source images
3. Where were you expecting the crops to be created?

**Comment by vtellez** [comment]
Thanks for your quicktime answer!

1. In our composer.json, bkwld/croppa": "~3.0",

2. Source images are in the same path of generated thumbs. /uploads/people/

3. At the same path as num 2

Thanks for your attention

**Comment by weotch** [comment]
1) I'm also wondering what exact version is installed.  Open up your composer.lock file and look for the part of it that is like:

```json
 {
            "name": "bkwld/croppa",
            "version": "3.6.2",
            "source": {
                "type": "git",
                "url": "https://github.com/BKWLD/croppa.git",
                "reference": "5452db2d5925b388b7adedd6fe9d9f772aca92e4"
            },
...
}
```

4) Assuming you are using `Croppa::url()` can you post an example of what arguments you are passing?

Thanks!

**Comment by vtellez** [comment]
1) from my composer.lock

"name": "bkwld/croppa",
            "version": "3.6.2",
            "source": {
                "type": "git",
                "url": "https://github.com/BKWLD/croppa.git",
                "reference": "5452db2d5925b388b7adedd6fe9d9f772aca92e4"
            },


4)

For calling Croppa I am calling like this:

Croppa::url('/uploads/people/avatar.png', $width, $height)



Should I update to Croppa v4.x?

**Comment by weotch** [comment]
Try changing the src_dirs to:

```
'src_dirs' => array(
    App::make('path.public').'/uploads',
),
```

If that doesn't work, yeah, I'd recommend you roll back to 3.4.x or upgrade to 4.0.  I'm pretty happy with 4.0 so if you don't mind a little upgrade work, I'd recommend the latter.

**Comment by vtellez** [comment]
This change for the config file seems not working :(

We will update to the 4.0. Is there any doc with the step to upgrade?

I supose we must:

1) Change composer.json to 4.0 vesion
2) Run composer update
3) Change config file with these one: https://github.com/BKWLD/croppa/blob/master/src/config/config.php

Right?

Are any changes in the calling of croppa::url?

Thanks in advance @weotch !

**Comment by weotch** [comment]
Yeah, that's about it.  No change to `Croppa::url()` api.

**Comment by vtellez** [comment]
Ooops, now its seem not working at all. Even, Croppa does not show the thumbnails that exists in the disk.

We are thinking to rollback to 3.4.x  How can we do that? I am not sure what should I edit in composer.json

Thanks again

**Comment by weotch** [comment]
In your composer.json, make it `'bkwld/croppa' : '~3.4.0'`.  Then run `composer update bkwld/croppa`

**Comment by vtellez** [comment]
Thanks @weotch. It's a pleasure find developers like you!

I rollback to 3.4.0 and it's working. I supose we stay here until we have enough time to see what is the problem. I think there will be a fail configuration.

Thanks

**Comment by weotch** [comment]
Thank @vtellez !

**Comment by insmod** [comment]
Just wanted to say that I have the same problem and I recurred to the same solution - rolling back to 3.4.0.

It stopped working some time ago, probably in the same update it stopped for @vtellez ...

I'm using Laravel 4.

Thanks for the great project, though! It's awesome and I really like that you take your time updating it over the years and answering to every issue. Great job!

**Comment by weotch** [comment]
Thanks @insmod !  I recommend upgrading to Croppa 4.0 if you can afford a little time to make the required tweaks.
