### ISSUE TITLE
Crops dir in the same folder as source dir

### ISSUE THREAD

**Issue by sushantaryal** [BKWLD/croppa#90]
I recently upgraded to 4.0, I like the feature where i can change the crops dir. Is it possible to create the crops dir inside the source dir.

**Comment by weotch** [comment]
It should be possible, though I didn't make an explicit test for that use case.  Lemme know how it goes!

**Comment by sushantaryal** [comment]
I was able to do that if I make my crops dir path absolute in the config. But if i change my crops_dir to 'public_path().'/uploads/thumbs' it doesn't work. Is there any solution to that?

**Comment by weotch** [comment]
Well, the two should be equivalent. Public_path() is the absolute path to your public dir. Can you provide an example of the absolute path that is working and then what public_path() returns? Thanks!


- Robert Reinhard

**Comment by sushantaryal** [comment]
My config file
```
'src_dir' => public_path().'/uploads',
'crops_dir' => public_path().'/uploads/wedental/blogs/thumbs',
```
It is working but the crops files are inside
`'uploads/wedental/blogs/thumbs/wedental/blogs'`
Still not satisfied, I want the crops_dir to be
`'uploads/wedental/blogs/thumbs'`
I am working on media manager so i can't provide absolute path to crops_dir

**Comment by weotch** [comment]
I see what you mean.  I'll take a look at this soon, but I could see it taking me till next week to resolve.

**Comment by sushantaryal** [comment]
Thank you

**Comment by weotch** [comment]
Hey there, sorry for the delay.  Have you tried this for your `path` in the config?

```php
'path' => 'uploads/wedental/blogs/thumbs/(.*)$'
```

I think that'll do the trick, lemme know how it goes.

**Comment by weotch** [comment]
I've looked into this more in the writing of [these examples](https://github.com/BKWLD/croppa/wiki/Examples) and I revised my comment above.
