### ISSUE TITLE
Crops are not being deleted

### ISSUE THREAD

**Issue by d-lamers** [BKWLD/croppa#95]
On Laravel 4.2 the crops are not being deleted while the original is being deleted

Origin name:
uploads/aranciata-san-benedetto-25cl.png
Crop name:
uploads/thumbs/aranciata-san-benedetto-25cl-130x130.png

    \Croppa::delete('uploads/'.$image->slug.'.png');

**Comment by d-lamers** [comment]
The problem seems to be with this line (223, Storage.php):

    }, array_values(array_filter($this->crops_disk->listContents(dirname($path)), 

When I change it to this, it works fine:

    }, array_values(array_filter($this->crops_disk->listContents(),

**Comment by weotch** [comment]
What is your `crops_dir` and `path` config?

**Comment by weotch** [comment]
I've only tested the above via unit tests, but it seems to fix what I was seeing.  Let me know how it goes for you.
